### ISSUE TITLE
my error in keypoints_loss

### ISSUE THREAD

**Issue by zyc4me** [Stick-To/Object-Detection-API-Tensorflow#1]
i met some error when i use the testcenternet.py

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 1. First element had shape [32,5] and element 7 had shape [30,5].
         [[node IteratorGetNext (defined at /home/zyc/work/experiment/tf_detection/CenterNet.py:63) ]]
         [[node center_detector/cond_13/SparseToDense (defined at /home/zyc/work/experiment/tf_detection/CenterNet.py:244) ]]`

and my config is
`lr = 0.001
batch_size = 8
buffer_size = 256
epochs = 300
reduce_lr_epoch = [180, 250]
config = {
    'mode': 'train',                                       # 'train', 'test'
    'input_size': 256,
    'data_format': 'channels_last',                        # 'channels_last' 'channels_first'
    'num_classes': 4,
    'weight_decay': 1e-4,
    'keep_prob': 0.5,                                      # not used
    'batch_size': batch_size,

    'score_threshold': 0.1,                                 
    'top_k_results_output': 100,                           

}

image_augmentor_config = {
    'data_format': 'channels_last',
    'output_shape': [256, 256],
    'zoom_size': [300, 300],
    'crop_method': 'random',
    'flip_prob': [0., 0.5],
    'fill_mode': 'BILINEAR',
    'keep_aspect_ratios': False,
    #'constant_values': 0.,
    'color_jitter_prob': 0.5,
    #'rotate': [0.5, -10., 10.],
    'pad_truth_to': 32,
}`

so can you help me ?

**Comment by Stick-To** [comment]
zoom_size is too big, after image augmention, there is no object in image

**Comment by Stick-To** [comment]
I am sorry, there is a small bug in Object-Detection-API-Tensorflow Repository, it is fixed now

here is the Repository for https://github.com/Stick-To/CenterNet-tensorflow alone
