### ISSUE TITLE
coordinate

### ISSUE THREAD

**Issue by jaminChen999** [Stick-To/Object-Detection-API-Tensorflow#10]
you seem don't normalize the coordinate into 1.

**Comment by Stick-To** [comment]
it not need, ground_truth and anchors are both not normalized. you can see the regression formula

**Comment by jaminChen999** [comment]
you compare the performance of normalization& no.




| |
陈志明
邮箱：15621426809@163.com
|

签名由 网易邮箱大师 定制

On 06/05/2019 09:56, Stick-To wrote:

it not need, ground_truth and anchors are both not normalized. you can see the regression formula

**Comment by Stick-To** [comment]
the coordinate is used to compute IOU, and the regression target (ground_truth/anchor), you could see that the normalization doesn't matter, all the values in the computational process are not changed.

**Comment by jaminChen999** [comment]
Ok,thanks.




| |
陈志明
邮箱：15621426809@163.com
|

签名由 网易邮箱大师 定制

On 06/05/2019 12:33, Stick-To wrote:

the coordinate is used to compute IOU, and the regression target (ground_truth/anchor), you could see that the normalization doesn't matter, all the values in the computational process are not changed.
