### ISSUE TITLE
pretrained weight issue 

### ISSUE THREAD

**Issue by yangweixiang** [Stick-To/Object-Detection-API-Tensorflow#15]
I try to reproduce FCOS paper result by use your code . After train and test , found the result not very good. And I found the backbone did not use the pretrained weights, like resnet_v1_50.ckpt. Does the bad result related with this ?

**Comment by Stick-To** [comment]
the pretraining is very important, and you could change the backone of model, the filters of the backone in my model is 1/4 of original resnet50
