### ISSUE TITLE
关于数据集格式的请教

### ISSUE THREAD

**Issue by Toney1995** [Stick-To/Object-Detection-API-Tensorflow#17]
作者用的应该是VOC2007数据集吧，我找到了那个数据集，打开里面有包括ImagineSets的若干文件夹，请问作者在项目中的voc2007文件夹里面是什么样子的？

**Comment by Stick-To** [comment]
可以xml放进一个文件夹，图片放进一个文件夹，也可以xml和图片放进放在一个文件夹里

**Comment by Toney1995** [comment]
作者你好，我按照你的方法尝试了一下，好像不太可以，可能是您没有明白我的问题，能不能麻烦您把您的data = [os.path.join('./voc2007', name) for name in data]下的voc2007文件夹和您的fcos权重发到857576157@QQ.com，非常感谢您的帮助

**Comment by Stick-To** [comment]
你要先生成tfrecord, ./voc2007 /内的是tfrecord, 权重我没有保留
