### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by Innan666** [Stick-To/Object-Detection-API-Tensorflow#19]
Invalid argument: Feature: ground_truth (data type: string) is required but could not be found.
在训练的时候出现上面报错请问是哪里出了问题

**Comment by Stick-To** [comment]
哪个网络？

**Comment by Stick-To** [comment]
看起来是数据读取有问题， 应该是tfrecord生成的错误，或者数据集格式错误

**Comment by Innan666** [comment]
网络是CenterNet  我开始用你的代码生成tfrecord不成功 我就用了别的生成了一下然后在你的testcenternet训练的

**Comment by Stick-To** [comment]
需要用我的代码生成tfrecord,

**Comment by Innan666** [comment]
对了 这些代码在Windows上行得通不

**Comment by Stick-To** [comment]
可以

**Comment by Stick-To** [comment]
路径对了就行了
