### ISSUE TITLE
Train  own dataset，exit code

### ISSUE THREAD

**Issue by AiIsBetter** [Stick-To/Object-Detection-API-Tensorflow#24]
FCOS
Process finished with exit code -1073741819 (0xC0000005)。
fcos.load_weight('./fcos/test-95778') ，I deleted this line. python 3.6.7 tf 1.13.0
cuda10.0. 
 Is there a mistake? Total training to fixed number of steps error .

**Comment by LaserLV52** [comment]
i have the same question with you. please tell me how to deal with this problem
