### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by dimitrius-ion** [Stick-To/Object-Detection-API-Tensorflow#25]
Hello,

Sorry for dumb question, but is there a way to include validation step after training each epoch? would it just calculate mean_loss on validation data set? how can it be used for  adjusting the weights? 

Thank you,
Dimitrius

**Comment by Stick-To** [comment]
After some train step or all train step, you can use test_one_image to validate, but there is no validation step during training. And test_one_image only give results for every image, no map calculatation
