### ISSUE TITLE
训练中tensorflow.python.framework.errors_impl.InvalidArgumentError: Reduction axis 1 is empty in shape [8828,0]

### ISSUE THREAD

**Issue by nistarlwc** [Stick-To/Object-Detection-API-Tensorflow#26]
您好，
我只用了voc2007数据集，使用项目中的test_voc_utils.py，生成的tfrecord。
在运行SSD300.py时，一开始可以训练，但多一会就会报错退出。先后换了tensorflow1.12和1.13版本，错误相同
>------------------------- epoch 2 -------------------------
> iters 262/312 loss 4.369279Traceback (most recent call last):
  File "/home/lwc/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/lwc/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/lwc/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reduction axis 1 is empty in shape [8828,0]
         [[{{node inference/while/ArgMax_1}} = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](inference/while/boolean_mask_5/GatherV2, inference/while/ArgMax_1/dimension)]]
         [[{{node inference/while/SparseTensor/dense_shape/_221}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1593_inference/while/SparseTensor/dense_shape", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopinference/while/SparseToDense/default_value/_5)]]

**Comment by Stick-To** [comment]
你的图像增强策略可能太过了

**Comment by nistarlwc** [comment]
@Stick-To 什么意思，image_augmentor_config参数有问题？我直接使用SSD300.py，并没有修改

**Comment by Stick-To** [comment]
把      'zoom_size': [320, 320],
注释掉 试试

**Comment by icoicqico** [comment]
have you fixed the problem? Because I have the same problem with retinanet.

**Comment by xiao-an-qi** [comment]
@nistarlwc  请问你的问题解决了吗？我把'zoom_size'注释掉也没用，’crop_method’换成‘center’也没用。

**Comment by berit99** [comment]
I have the same problem and couldn't fix the issue for now.

**Comment by lvZic** [comment]
have u fixed it?
