### ISSUE TITLE
how to convert xml to tfrecord during training ?

### ISSUE THREAD

**Issue by keithyh** [Stick-To/Object-Detection-API-Tensorflow#29]
Hi, I am using your centernet code,but there are no comments in the code so I do not know how to perform training. 

My data format is standard pascal VOC xml files.However I cannot see xml processing code in testcenternet.py. Can you help me?Thank you!

**Comment by Stick-To** [comment]
https://github.com/Stick-To/CenterNet-tensorflow/blob/master/utils/tfrecord_voc_utils.py

**Comment by keithyh** [comment]
Thank you! Can you provide an example using the xml_to_example function and the dataset2tfrecord function in this file?

**Comment by Stick-To** [comment]
xml_to_example function is used in dataset2tfrecord 
and the using of dataset2tfrecord  is in 
https://github.com/Stick-To/Object-Detection-API-Tensorflow/blob/master/utils/test_voc_utils.py

**Comment by keithyh** [comment]
Thank you!Can you provide detailed steps on how to train one's own data for CenterNet.My own data is in xml format.By doing so ,I think your code will become much more popular.

**Comment by Stick-To** [comment]
I have modified the readme of Object-Detection-API-Tensorflow, all the models could follow these steps

**Comment by keithyh** [comment]
Okay! That sounds great! I will have a try.If no problem persists,you've done a really excellent job！
