### ISSUE TITLE
Where do you use the generated tfrecord file?

### ISSUE THREAD

**Issue by keithyh** [Stick-To/Object-Detection-API-Tensorflow#30]
After running test_voc_utils.py some tfrecord files were generated,however these tfrecord files seems not used in testcenternet.py

**Comment by Stick-To** [comment]
![12](https://user-images.githubusercontent.com/34546552/64324858-b317d280-cff9-11e9-9d88-cce3ec86995e.PNG)

**Comment by keithyh** [comment]
I probably understood  that the path ./voc2007/ in the above snapshot should be path of the tfrecord files generated by running test_voc_utils.py.

After changing ./voc2007/ to r'D:\bu\tfrecord' which is  actual  path of my tfrecord files,I still got errors below.

Why does this error occur?


Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.4.0 -- An enhanced Interactive Python.

runfile('D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master/testcenternet.py', wdir='D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master')
WARNING: Logging before flag parsing goes to stderr.
W0905 16:30:31.336427  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\utils\tfrecord_voc_utils.py:153: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

W0905 16:30:31.343424  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\utils\tfrecord_voc_utils.py:154: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

W0905 16:30:31.396901  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\utils\image_augmentor.py:117: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

W0905 16:30:31.414890  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\utils\image_augmentor.py:131: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0905 16:30:33.253837  6236 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0905 16:30:33.434808  6236 deprecation.py:323] From D:\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0905 16:30:33.774861  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\utils\tfrecord_voc_utils.py:176: The name tf.data.Iterator is deprecated. Please use tf.compat.v1.data.Iterator instead.

W0905 16:30:33.774861  6236 deprecation.py:323] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\utils\tfrecord_voc_utils.py:176: DatasetV1.output_types (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(dataset)`.
W0905 16:30:33.774861  6236 deprecation.py:323] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\utils\tfrecord_voc_utils.py:176: DatasetV1.output_shapes (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(dataset)`.
W0905 16:30:33.774861  6236 deprecation.py:323] From D:\Anaconda3\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py:348: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
W0905 16:30:33.774861  6236 deprecation.py:323] From D:\Anaconda3\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py:349: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
W0905 16:30:33.774861  6236 deprecation.py:323] From D:\Anaconda3\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py:351: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
W0905 16:30:33.774861  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:41: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

W0905 16:30:33.790485  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:70: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0905 16:30:33.790485  6236 deprecation.py:323] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:343: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
W0905 16:30:33.790485  6236 deprecation.py:506] From D:\Anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0905 16:30:34.062977  6236 deprecation.py:323] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:332: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
W0905 16:30:34.620997  6236 deprecation.py:323] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:412: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
W0905 16:30:35.788212  6236 deprecation.py:323] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:422: average_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.AveragePooling2D instead.
W0905 16:30:37.288661  6236 deprecation.py:323] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:358: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2DTranspose` instead.
W0905 16:30:48.037235  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:154: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

W0905 16:30:55.296688  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:280: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0905 16:30:57.357138  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:286: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

W0905 16:30:57.357138  6236 deprecation_wrapper.py:119] From D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:287: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

------------------------- epoch 0 -------------------------
reduce lr, lr= 0.0001 now
Traceback (most recent call last):

  File "<ipython-input-1-102bddff4976>", line 1, in <module>
    runfile('D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master/testcenternet.py', wdir='D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master')

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master/testcenternet.py", line 76, in <module>
    mean_loss = centernet.train_one_epoch(lr)

  File "D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py", line 295, in train_one_epoch
    _, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Need minval < maxval, got 0 >= -208
	 [[{{node random_uniform_1}}]]
	 [[IteratorGetNext]]
	 [[center_detector/cond_59/SparseToDense/_829]]
  (1) Invalid argument: Need minval < maxval, got 0 >= -208
	 [[{{node random_uniform_1}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

**Comment by Stick-To** [comment]
Is your tensorflow is tf2.0
my code could not used in tf2.0
use tf1.14 tf1.13 tf1.12

**Comment by keithyh** [comment]
![是](https://user-images.githubusercontent.com/14086114/64326495-a47eea80-cffc-11e9-8925-f9088ed2b665.jpg)

**Comment by keithyh** [comment]
As shown in the picture,I am using tensorflow-gpu 1.14.0

**Comment by keithyh** [comment]
![t](https://user-images.githubusercontent.com/14086114/64326589-d7c17980-cffc-11e9-88bf-ea4f6dc7097f.jpg)

**Comment by Stick-To** [comment]
windows should use
'D:\\bu\\tfrecord

**Comment by keithyh** [comment]
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Need minval < maxval, got 0 >= -208
	 [[{{node random_uniform_1}}]]
	 [[IteratorGetNext]]
	 [[center_detector/cond_123/SparseToDense/_1685]]
  (1) Invalid argument: Need minval < maxval, got 0 >= -208
	 [[{{node random_uniform_1}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

**Comment by keithyh** [comment]
my os is windows 10. After changed to 'D:\\bu\\tfrecord\\',still got the same error above

**Comment by keithyh** [comment]
my os is windows 10. After changed to 'D:\\bu\tfrecord\\',still got the same error above

**Comment by Stick-To** [comment]
'D:\\\bu\\\tfrecord'

**Comment by keithyh** [comment]
Yes. After changed to 'D:\\\\bu\\\\tfrecord\\\\' or  'D:\\\\bu\\\\tfrecord'  still got the same error above

**Comment by keithyh** [comment]
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Need minval < maxval, got 0 >= -208
	 [[{{node random_uniform}}]]
	 [[IteratorGetNext]]
	 [[center_detector/cond_59/SparseToDense/_829]]
  (1) Invalid argument: Need minval < maxval, got 0 >= -208
	 [[{{node random_uniform}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

**Comment by Stick-To** [comment]
![12](https://user-images.githubusercontent.com/34546552/64328817-bd899a80-d000-11e9-9e02-9d94f51802ca.PNG)

your tfrecord generation may be wrong
