### ISSUE TITLE
Hello, could you share me the YOLO-v3 pretrained model? plz

### ISSUE THREAD

**Issue by QianSunCN** [Stick-To/Object-Detection-API-Tensorflow#34]
Hello, thank you for your work first !  
I want to train my dataset use YOLOv3, It is very hard to train the model from scratch with no pretrained model...could you share me the YOLO-v3 pretrained model? Thank you very mych!

**Comment by Stick-To** [comment]
sorry， I did not keep  it

**Comment by QianSunCN** [comment]
> sorry， I did not keep it

Thank you
