### ISSUE TITLE
Shape mismatch problem

### ISSUE THREAD

**Issue by gulingfengze** [Stick-To/Object-Detection-API-Tensorflow#35]
Hello, I encountered a problem when training with my own training data set: the training image size was 384x384, the picture was three-way, standard voc format data was used for training, and testcenternet.py was used for training, and the following error was reported:

Tensorflow. Python. Framework. Errors_impl. InvalidArgumentError: Input to reshape is a tensor with 442368 values, but the requested shape from 147456

[[{{node Reshape_2}}]]

[[{{node IteratorGetNext}}]]

[[{{node IteratorGetNext}}]]

I don't know why the shape mismatching is reported. I hope to get your help. Thank you!

**Comment by Stick-To** [comment]
may #28 could help you
