### ISSUE TITLE
train problem,a valid checkpoint????

### ISSUE THREAD

**Issue by weiwandege77** [Stick-To/Object-Detection-API-Tensorflow#37]
C:\Users\kzz\AppData\Local\Programs\Python\Python37\python.exe Y:/Models/Object-Detection-API-Tensorflow-master/testrefinedet.py
WARNING:tensorflow:From C:\Users\kzz\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From Y:\Models\Object-Detection-API-Tensorflow-master\RefineDet.py:671: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.max_pooling2d instead.
WARNING:tensorflow:From Y:\Models\Object-Detection-API-Tensorflow-master\RefineDet.py:642: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d instead.
WARNING:tensorflow:From Y:\Models\Object-Detection-API-Tensorflow-master\RefineDet.py:620: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.batch_normalization instead.
WARNING:tensorflow:From Y:\Models\Object-Detection-API-Tensorflow-master\RefineDet.py:657: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d_transpose instead.
WARNING:tensorflow:From C:\Users\kzz\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\losses\losses_impl.py:209: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From C:\Users\kzz\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
C:\Users\kzz\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\gradients_impl.py:110: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2019-10-08 17:19:51.745878: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\Users\kzz\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "Y:/Models/Object-Detection-API-Tensorflow-master/testrefinedet.py", line 62, in <module>
    refinedet.load_weight('./refinedet320/test-1092')
  File "Y:\Models\Object-Detection-API-Tensorflow-master\RefineDet.py", line 613, in load_weight
    self.saver.restore(self.sess, path)
  File "C:\Users\kzz\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\training\saver.py", line 1268, in restore
    + compat.as_text(save_path))
**ValueError: The passed save_path is not a valid checkpoint: ./refinedet320/test-1092**

**Comment by Stick-To** [comment]
you could delete this
refinedet.load_weight('./refinedet320/test-1092')

my weight is not keeped
