### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by xiao-an-qi** [Stick-To/Object-Detection-API-Tensorflow#39]
when i use your centernet for my dataset(600*600*3), the testcenternet throw out the problem: ValueError: Dimensions must be equal, but are 75 and 76 for 'upsampling/add_1' (op: 'Add') with input shapes: [8,75,75,256], [8,76,76,256]
can you help? thanks!

**Comment by Stick-To** [comment]
change size // 32 == 0
