### ISSUE TITLE
can you provide pretrain weights for centernet?

### ISSUE THREAD

**Issue by LCWdmlearning** [Stick-To/Object-Detection-API-Tensorflow#4]
I want to retrain centernet on the new dataset(small).
Because if I train the model with coco data, it will take too much time.
so ,can you provide pretrain weights(coco) for centernet? I'll be very grateful.

**Comment by Stick-To** [comment]
I have not the pretrained weights on coco, I only pretrained the model on imagenet several epochs.
If you need, download it from here, 

https://pan.baidu.com/s/1xxBewJYHmV3u_h2O8S5ozg 
Extraction code:uo4u

**Comment by LCWdmlearning** [comment]
Thank you anyway.
