### ISSUE TITLE
loss nan

### ISSUE THREAD

**Issue by xiao-an-qi** [Stick-To/Object-Detection-API-Tensorflow#41]
请问下，我在训练centernet的时候，设置lr为0.0001，batch_size为4，第一个epoch时运行到三分之一不到就显示 loss nan，何故？先谢过！

**Comment by m-wei** [comment]
me too! FCOS is the same..

**Comment by Stick-To** [comment]
https://github.com/Stick-To/CenterNet-tensorflow/issues/20
could this help you?

**Comment by xiao-an-qi** [comment]
thanks a lot, I'll try it!

**Comment by DLH06** [comment]
@Andy457 did u fix it? I get the same thing and i follow this issue above but nothing changes.

**Comment by xiao-an-qi** [comment]
@DLH06 yeah,it works for me.
