### ISSUE TITLE
problems with the generation of tfrecords

### ISSUE THREAD

**Issue by vkhvorostianyi** [Stick-To/Object-Detection-API-Tensorflow#45]
Hey, there are some problems with the generation of tfrecords
```
Traceback (most recent call last):
  File "test_voc_utils.py", line 8, in <module>
    import utils.tfrecord_voc_utils as voc_utils
ModuleNotFoundError: No module named 'utils'
```
I've just added `__init__.py` to the utils folder and fixed import in related files by deleting `utils` before the inner object. So, believe it'll help someone.

**Comment by zcunyi** [comment]
> Hey, there are some problems with the generation of tfrecords
> 
> ```
> Traceback (most recent call last):
>   File "test_voc_utils.py", line 8, in <module>
>     import utils.tfrecord_voc_utils as voc_utils
> ModuleNotFoundError: No module named 'utils'
> ```
> 
> I've just added `__init__.py` to the utils folder and fixed import in related files by deleting `utils` before the inner object. So, believe it'll help someone.

hi, have you trained on your own data with centernet success?

**Comment by vkhvorostianyi** [comment]
used the VOC dataset. THE PYTHONPATH along init adding solved the problem.
