### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [9,1] vs. shape[2] = [8,1] testutils genered corrupted tf records

### ISSUE THREAD

**Issue by vkhvorostianyi** [Stick-To/Object-Detection-API-Tensorflow#46]
```
Traceback (most recent call last):
  File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [9,1] vs. shape[2] = [8,1]
         [[{{node concat_1}}]]
         [[{{node IteratorGetNext}}]]
         [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testrefinedet.py", line 68, in <module>
    mean_loss = refinedet.train_one_epoch(lr)
  File "/home/vkhvorostianyi/Object-Detection-API-Tensorflow/RefineDet.py", line 587, in train_one_epoch
    _, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})
  File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [9,1] vs. shape[2] = [8,1]
         [[{{node concat_1}}]]
         [[node IteratorGetNext (defined at /home/vkhvorostianyi/Object-Detection-API-Tensorflow/RefineDet.py:63) ]]
         [[node IteratorGetNext (defined at /home/vkhvorostianyi/Object-Detection-API-Tensorflow/RefineDet.py:63) ]]
```
The problem is address to code for VOC dataset, dunno about the rest

**Comment by zcunyi** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
>     return fn(*args)
>   File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [9,1] vs. shape[2] = [8,1]
>          [[{{node concat_1}}]]
>          [[{{node IteratorGetNext}}]]
>          [[{{node IteratorGetNext}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "testrefinedet.py", line 68, in <module>
>     mean_loss = refinedet.train_one_epoch(lr)
>   File "/home/vkhvorostianyi/Object-Detection-API-Tensorflow/RefineDet.py", line 587, in train_one_epoch
>     _, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})
>   File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
>     run_metadata_ptr)
>   File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
>     run_metadata)
>   File "/home/vkhvorostianyi/anaconda3/envs/refinedet_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [9,1] vs. shape[2] = [8,1]
>          [[{{node concat_1}}]]
>          [[node IteratorGetNext (defined at /home/vkhvorostianyi/Object-Detection-API-Tensorflow/RefineDet.py:63) ]]
>          [[node IteratorGetNext (defined at /home/vkhvorostianyi/Object-Detection-API-Tensorflow/RefineDet.py:63) ]]
> ```
> 
> The problem is address to code for VOC dataset, dunno about the rest

have you solved the problem?

**Comment by vkhvorostianyi** [comment]
Yep, I've solved, I used the code from RefineDet repo. thanks

**Comment by KapilM26** [comment]
Hey, I am having the same problem, please let me know what you have done.
Thanks

**Comment by lvZic** [comment]
> Yep, I've solved, I used the code from RefineDet repo. thanks

Hey, I am having the same problem, please let me know what you have done.
Thanks

**Comment by lvZic** [comment]
> Hey, I am having the same problem, please let me know what you have done.
> Thanks

Hey, I am having the same problem, please let me know what you have done.
Thanks
