### ISSUE TITLE
would you mind sharing your pretrained model like yolov3 FCOS CenterNet?

### ISSUE THREAD

**Issue by huangxiaosa** [Stick-To/Object-Detection-API-Tensorflow#48]

**Comment by Shoshin23** [comment]
That would be super useful, if you could share some of the pre-trained models so we can test inference times before attempting to train on our own dataset.

**Comment by shenyingying** [comment]
@Shoshin23 have you get the pre-trained models,can you share with me,thanks a lot!

**Comment by huangxiaosa** [comment]
> @Shoshin23 have you get the pre-trained models,can you share with me,thanks a lot!

not yet
