### ISSUE TITLE
anchor variance

### ISSUE THREAD

**Issue by jaminChen999** [Stick-To/Object-Detection-API-Tensorflow#8]
I see your code, I find that you don't add variance when you encode box

**Comment by Stick-To** [comment]
which network?

**Comment by jaminChen999** [comment]
ssd, refinedet
        pos_truth_pbbox_yx = (total_pos_gbbox_yx - total_pos_abbox_yx) / total_pos_abbox_hw
        pos_truth_pbbox_hw = tf.log(total_pos_gbbox_hw / total_pos_abbox_hw
soure code:
        pos_truth_pbbox_yx = (total_pos_gbbox_yx - total_pos_abbox_yx) / total_pos_abbox_hw / 0.1
        pos_truth_pbbox_hw = tf.log(total_pos_gbbox_hw / total_pos_abbox_hw / 0.2

**Comment by Stick-To** [comment]
I have never see the source code, only implement network according to paper

**Comment by jaminChen999** [comment]
👍




| |
陈志明
邮箱：15621426809@163.com
|

签名由 网易邮箱大师 定制

On 05/29/2019 19:09, Stick-To wrote:

I have never see the source code, only implement network according to paper
